version: '3'

services:
  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    ports:
      - "8080:8080"
    command: gunicorn -w 1 -b 0.0.0.0:8080 app:server
    volumes:
      - ./data:/home/data

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - dash_app
    volumes:
      - ./nginx/public:/var/www/html
      - ./nginx/conf.d.http:/etc/nginx/conf.d
