import dash_core_components as dcc
import dash_html_components as html

import dash_bootstrap_components as dbc

import pathlib
import page_builder as pb
from settings import *
from charts import empty_chart, figure_2_16, figure_2_17, map_2_9

chapter_num = '2.9'
bannerImgSrc = IMAGES_PATH+'AtmosphericSections/Lightning_Noel_Fitzpatrick_storm_chasing_2019_day7_lightning_stack_LR_brighter.jpg'
bannerImgCredit = 'Noel Fitzpatrick'

introText = """
Lightning is a powerful discharge of energy that occurs during an electric 
storm and is often only noted by the associated thunder. This phenomenon may 
cause loss of life and destruction, such as vegetation fires and damage to 
buildings, electrical infrastructure and other sectors. However, the impacts 
due to the storms which generate lightning are normally bigger than those 
caused by the lightning itself. The direct link between storms and lightning 
makes this parameter a key indicator to understand the behaviour or variation 
of storms. Variations of lightning frequency may be a consequence of climate 
change and an increase in the number of lightning events affects the climate 
directly by producing nitrogen oxides (NOx), which can react to form N\u2082O a 
strong greenhouse gas. 
        """
bulletPoint1 = """
Lightning shows very large inter-annual variability, with the majority of the 
strikes occurring during summer months. 
        """
bulletPoint2 = """
Valentia Observatory is a flagship weather station making the only lightning 
observations in Ireland.
        """
bulletPoints = [bulletPoint1, bulletPoint2]
# trendChartTitle = ''
# trendChart = figure_2_17()

# trendCaption = """
# Number of 15 minute lightning pulses detected by the ATDnet Lightning system for 26th – 27th May 2018 allows the trajectory of a thunderstorm to be tracked.  
#         """

infrastructureText = """
Lightning measurements have been taken by Met Éireann at Valentia Observatory, 
Co. Kerry since 2007, as part of the ATDnet Lightning System, an 
international network administrated by the UK Met office. This network is 
composed of a global set of sensors the majority located in Western Europe. 
Each sensor detects a pulse of electromagnetic energy generated by a lightning 
strike, which can travel distances up to 10000 km.   The location of a 
lightning strike can be determined based on the combination of differences in 
time taken for the pulse to reach each sensor. 
Lightning can also be inferred by satellite observations from instruments such 
as the Lightning Imaging Sensor (LIS) on board the International Space Station 
(ISS) or the Global Lightning Mapper (GLM) on board the GOES-16 geostationary 
satellite. 

        """
infrastructureMap = map_2_9()

infoLinks = [
    {'text': 'Lightning Essential Climate Variable (ECV) Factsheet',
     'url': 'https://gcos.wmo.int/en/essential-climate-variables/lightning'},
     {'text': 'Met Éireann information on lightning measurements at Valentia Observatory',
     'url': 'https://www.met.ie/science/valentia/lightning-detection'},
     {'text': 'Met Éireann information on data availability',
     'url': 'https://www.met.ie/climate/what-we-measure/lightning'},
     {'text': 'Met Office ATDNet system lightning strike location data sheet',
     'url': 'https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/pdf/data/adtnet_data_sheet.pdf)'},
     {'text': 'Information about NASA lightning space search and observations',
     'url': 'https://ghrc.nsstc.nasa.gov/lightning/space-search-observations.html'},

]


########################################################################################################################
chapter_dict = next(
    (item for item in CHAPTERS if item['chapter-num'] == chapter_num), None)

trendChartTitle1 = '10-Day Accumulated Number of Lightning Pulses'
trendChart1 = figure_2_16()
trendCaption1 = """
10-Day accumulated lighting pulses over a) the whole Irish Shelf and b) the 
land area from the ATDnet Lightning System, for the period 2001 to 2019.
Most of the lightning strikes are at sea, with only 15% occurring over land. 
During winter, lightning occurrence is at a minimum, due to the reduced amount 
of energy available due to the lack of solar heating and available atmospheric 
water vapour. The majority of lightning pulses are observed in summer and are 
related to electrical storms with power outages being the most common impact 
in Ireland. 
        """

trendChartTitle2 = 'Lightning Storm Tracking with ATDnet Data'
trendChart2 = figure_2_17()
trendCaption2 = """
Number of lightning pulses, grouped in 15min intervals, detected by the ATDnet 
Lightning system 
for 26th – 27th May 2018 allows the trajectory of a thunderstorm to be tracked.
The storm originated over the sea late evening and around midnight moved over 
the south coast, spreading towards the east, with maximum lightning activity 
occurring between 4:00am and 5:00am. Click play or drag slider to animate.
        """

custom_trend = dbc.Container(
        className='sr-trends',
        style={'borderColor': chapter_dict['domain-color']},
        id='trends',
        children=[
            html.H3(
                className='sr-section-heading',
                style={'color': chapter_dict['domain-color']},
                children='Trends',
            ),
            dbc.Row(
                children=[
                    dbc.Col(className="col-md-10 offset-md-1",
                            children=[
                                html.H4(
                                    className='sr-chart-title',
                                    children=trendChartTitle1),
                                dcc.Graph(
                                    figure=trendChart1,
                                    id='chart'+chapter_dict['href'],
                                    config={'displayModeBar': False})]
                            )
                ]
            ),
            dbc.Row(
                children=[
                    dbc.Col(className="col-md-10 offset-md-1",
                            children=[
                                html.P(
                                    className='sr-chart-caption',
                                    children=[
                                        html.I(className="fas fa-play _up",
                                               style={"color": chapter_dict['domain-color']}),
                                        trendCaption1]
                                )]
                            )
                ]
            ),
            dbc.Row(
                children=[
                    dbc.Col(className="col-md-10 offset-md-1",
                            children=[
                                html.H4(
                                    className='sr-chart-title',
                                    children=trendChartTitle2),
                                dcc.Graph(
                                    figure=trendChart2,
                                    id='chart'+chapter_dict['href'],
                                    config={'displayModeBar': False})]
                            )
                ]
            ),
            dbc.Row(
                children=[
                    dbc.Col(className="col-md-10 offset-md-1",
                            children=[
                                html.P(
                                    className='sr-chart-caption',
                                    children=[
                                        html.I(className="fas fa-play _up",
                                               style={"color": chapter_dict['domain-color']}),
                                        trendCaption2]
                                )]
                            )
                ]
            )])

def create_layout(app):
    return html.Div(
        children=[
            pb.build_banner(bannerImgSrc,
                            bannerImgCredit,
                            chapter_dict
                            ),
            pb.build_breadcrumb(chapter_dict),
            pb.build_nav(chapter_dict),
            pb.build_intro(introText,
                           bulletPoints,
                           chapter_dict
                           ),
            custom_trend,
        #     pb.build_trend(trendChartTitle,
        #                    trendChart,
        #                    trendCaption,
        #                    chapter_dict
        #                    ),
            pb.build_infrastructure(infrastructureText,
                                    infrastructureMap,
                                    chapter_dict
                                    ),
            pb.build_info(infoLinks,
                          chapter_dict),

            pb.build_nav_carousel(chapter_dict)
        ])
